name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Executa todos os dias à meia-noite
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate GitHub snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: pedro162
          outputs: |
            ./output/github-contribution-grid-snake.svg
            ./output/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Commit and push
        uses: EndBug/add-and-commit@v9
        with:
          message: "generate contribution graph with snake"
          add: "output"
